export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      img: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
      name: "Electronics",
      desc: "Latest gadgets & tech",
      totalProducts: 150,
      buttonText: "Explore",
      bannerHead: "Tech World",
      bannerPara: "Discover the latest gadgets and innovative technology",
      badge: "Electronics Collection",
      icon: "IconDeviceLaptop",
      stats: [
        { icon: "IconCpu", title: "50+", subtitle: "Laptops & PCs" },
        { icon: "IconPhone", title: "70+", subtitle: "Smartphones" },
        { icon: "IconHeadphones", title: "30+", subtitle: "Audio Devices" },
      ],
    },
    {
      id: 2,
      img: "https://media.istockphoto.com/id/1153107514/photo/fashion-blogger-working-with-laptop-workspace-with-female-accessory-cosmetics-products-on.jpg?s=612x612&w=0&k=20&c=OuH0p_vfSWver87ns95z6hW68RBaO_otCmyN5wnrEeg=",
      name: "Fashion",
      desc: "Trendy clothes & accessories",
      totalProducts: 89,
      buttonText: "Explore",
      bannerHead: "Fashion Trends",
      bannerPara: "Stay stylish with the latest fashion collections",
      badge: "Fashion Collection",
      icon: "IconShirt",
      stats: [
        { icon: "IconShirt", title: "40+", subtitle: "Clothing Items" },
        { icon: "IconShoe", title: "25+", subtitle: "Footwear" },
        { icon: "IconShoppingBag", title: "24+", subtitle: "Accessories" },
      ],
    },
    {
      id: 3,
      img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      name: "Home Decor",
      desc: "Make your space beautiful",
      totalProducts: 73,
      buttonText: "Explore",
      bannerHead: "Home Inspirations",
      bannerPara: "Beautify your home with our curated decor items",
      badge: "Home Decor Collection",
      icon: "IconHome",
      stats: [
        { icon: "IconLamp", title: "20+", subtitle: "Lighting" },
        { icon: "IconSofa", title: "30+", subtitle: "Furniture" },
        { icon: "IconPlant", title: "23+", subtitle: "Decor Items" },
      ],
    },
    {
      id: 4,
      img: "https://t4.ftcdn.net/jpg/02/73/55/33/360_F_273553300_sBBxIPpLSn5iC5vC8FwzFh6BJDKvUeaC.jpg",
      name: "Beauty",
      desc: "Cosmetics & personal care",
      totalProducts: 64,
      buttonText: "Explore",
      bannerHead: "Beauty Essentials",
      bannerPara: "Enhance your beauty with our top products",
      badge: "Beauty Collection",
      icon: "IconHeart",
      stats: [
        { icon: "IconBrush", title: "25+", subtitle: "Makeup Items" },
        { icon: "IconBottle", title: "20+", subtitle: "Skincare" },
        { icon: "IconScissors", title: "19+", subtitle: "Hair Care" },
      ],
    },
    {
      id: 5,
      img: "https://img.freepik.com/free-photo/sports-tools_53876-138077.jpg?semt=ais_hybrid&w=740&q=80",
      name: "Sports",
      desc: "Fitness & outdoor gear",
      totalProducts: 42,
      buttonText: "Explore",
      bannerHead: "Active Lifestyle",
      bannerPara: "Gear up for fitness and outdoor adventures",
      badge: "Sports Collection",
      icon: "IconBasketball",
      stats: [
        { icon: "IconRun", title: "15+", subtitle: "Fitness Gear" },
        { icon: "IconBallFootball", title: "12+", subtitle: "Sports Balls" },
        { icon: "IconBike", title: "15+", subtitle: "Outdoor Equipment" },
      ],
    },
    {
      id: 6,
      img: "https://media.istockphoto.com/id/1334436084/photo/top-down-view-of-colorful-illuminated-gaming-accessories-laying-on-table.jpg?s=612x612&w=0&k=20&c=E9xnbAZoBS5LlUX0q-zxT_3m6gEZpyB2k51_U4LLMNs=",
      name: "Gaming",
      desc: "Gaming gear & accessories",
      totalProducts: 85,
      buttonText: "Explore",
      bannerHead: "Gaming Arena",
      bannerPara: "Level up with the latest gaming accessories",
      badge: "Gaming Collection",
      icon: "IconGamepad",
      stats: [
        { icon: "IconDeviceGamepad2", title: "35+", subtitle: "Consoles" },
        { icon: "IconDeviceGamepad", title: "30+", subtitle: "Controllers" },
        { icon: "IconHeadset", title: "20+", subtitle: "Gaming Headsets" },
      ],
    },
    {
      id: 7,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvx871sN2kTOQmnzE8N2Aia9hSYQME6pdIfQ&s",
      name: "Accessories",
      desc: "Fashion & daily essentials",
      totalProducts: 62,
      buttonText: "Explore",
      bannerHead: "Essential Accessories",
      bannerPara: "Complete your look with trendy accessories",
      badge: "Accessories Collection",
      icon: "IconHandbag",
      stats: [
        { icon: "IconDeviceWatch", title: "20+", subtitle: "Watches" },
        { icon: "IconSunglasses", title: "22+", subtitle: "Sunglasses" },
        { icon: "IconWallet", title: "20+", subtitle: "Wallets" },
      ],
    },
    {
      id: 8,
      img: "https://i.pinimg.com/564x/21/a8/5c/21a85cf6a362aeda600f07ce7e41f939.jpg",
      name: "Baby & Kids",
      desc: "Everything for little ones",
      totalProducts: 94,
      buttonText: "Explore",
      bannerHead: "Little Wonders",
      bannerPara: "Find the perfect items for your little ones",
      badge: "Kids Collection",
      icon: "IconBabyCarriage",
      stats: [
        { icon: "IconBabyBottle", title: "30+", subtitle: "Baby Care" },
        { icon: "IconPuzzle", title: "34+", subtitle: "Toys" },
        { icon: "IconShirt", title: "30+", subtitle: "Kids Clothing" },
      ],
    },
    {
      id: 9,
      img: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
      name: "Music",
      desc: "Musical instruments & audio",
      totalProducts: 56,
      buttonText: "Explore",
      bannerHead: "Music World",
      bannerPara: "Explore instruments and audio gear for every musician",
      badge: "Music Collection",
      icon: "IconMusic",
      stats: [
        { icon: "IconMusic", title: "20+", subtitle: "Guitars" },
        { icon: "IconPiano", title: "15+", subtitle: "Keyboards" },
        { icon: "IconMicrophone", title: "21+", subtitle: "Audio Gear" },
      ],
    },
    {
      id: 10,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkI9Qd1V4WD7nB1pXic6VvY5jXncDTgvfFQA&s",
      name: "Photography",
      desc: "Cameras & photo equipment",
      totalProducts: 73,
      buttonText: "Explore",
      bannerHead: "Capture Moments",
      bannerPara: "Get the best cameras and photography tools",
      badge: "Photography Collection",
      icon: "IconCamera",
      stats: [
        { icon: "IconCamera", title: "30+", subtitle: "Cameras" },
        { icon: "IconDeviceCctv", title: "25+", subtitle: "Lenses" },
        { icon: "IconDrone", title: "18+", subtitle: "Drones" },
      ],
    },
    {
      id: 11,
      img: "https://www.nobiliaindia.com/images/modern-k/414_laser.jpg",
      name: "Kitchen",
      desc: "Kitchen appliances & tools",
      totalProducts: 108,
      buttonText: "Explore",
      bannerHead: "Kitchen Essentials",
      bannerPara: "Equip your kitchen with the best tools and appliances",
      badge: "Kitchen Collection",
      icon: "IconChefHat",
      stats: [
        { icon: "IconHomeCog", title: "35+", subtitle: "Appliances" },
        { icon: "IconCup", title: "40+", subtitle: "Cookware" },
        { icon: "IconCup", title: "33+", subtitle: "Utensils" },
      ],
    },
    {
      id: 12,
      img: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80",
      name: "Books",
      desc: "Novels, self-help & more",
      totalProducts: 101,
      buttonText: "Explore",
      bannerHead: "Knowledge Library",
      bannerPara:
        "Expand your mind with our curated collection of educational and inspiring books",
      badge: "Books Collection",
      icon: "IconBook",
      stats: [
        { icon: "IconBook", title: "40+", subtitle: "Fiction" },
        { icon: "IconBook2", title: "35+", subtitle: "Non-Fiction" },
        { icon: "IconBookDownload", title: "26+", subtitle: "E-Books" },
      ],
    },
  ]);
}
